versionCode=1008007
versionName=1.8.7
repoOwner=Lollo176ITA
repoName=Manga-dowloader
apkAssetName=app-release.apk
releaseNotes= fix 
updateConfigUrl=https://raw.githubusercontent.com/Lollo176ITA/Manga-dowloader/main/android-app/version.properties
