versionCode=1008005
versionName=1.8.5
repoOwner=Lollo176ITA
repoName=Manga-dowloader
apkAssetName=app-release.apk
releaseNotes= feat: implement auto reader speed settings and add page reading analyzer for improved reading experience
updateConfigUrl=https://raw.githubusercontent.com/Lollo176ITA/Manga-dowloader/main/android-app/version.properties
