versionCode=16
versionName=1.4.2
repoOwner=Lollo176ITA
repoName=Manga-dowloader
apkAssetName=app-release.apk
updateConfigUrl=https://raw.githubusercontent.com/Lollo176ITA/Manga-dowloader/main/android-app/version.properties
